# Site settings
title: 고도 gxdxt 
url: "https://gxdxt.github.io"
baseurl: ""
description: >
   gxdxt blog 

# My information
email: yxxsxxny@gmail.com
author: gxdxt 
profile: Unknown 
twitter_username: gxdxt 
github_username: gxdxt
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: gxdxt 
  shortname: b
utterances:
  repo: gxdxt/gxdxt.github.io
  issue-term: url
  label: Comment
  branch: master

google_analytics:
  ua: SAMPLE-VALUE
  encrypted_ua: THIS-IS-SAMPLE-VALUE

google_adsense:
  client: SAMPLE-VALUE

blame: "https://github.com/gxdxt/gxdxt.github.io/blame/master/_wiki"
edit: "https://github.com/gxdxt/gxdxt.github.io/edit/master/_wiki"
issue: "https://github.com/gxdxt/gxdxt.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
